javaVersion=21
kotlinVersion=2.4.10
intellijPlatformGradlePluginVersion=2.18.1

targetIdeVersion=2025.3
sinceBuild=253

flutterPluginVersion=96.0.0
dartPluginVersion=509.0.0

kotlin.stdlib.default.dependency=false
org.gradle.jvmargs=-Xmx4g
org.gradle.caching=true
org.gradle.configuration-cache=true
