name: build

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew check buildPlugin verifyPluginProjectConfiguration
      - if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports
          path: build/reports/tests

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew verifyPlugin
      - if: always()
        uses: actions/upload-artifact@v7
        with:
          name: plugin-verifier-report
          path: build/reports/pluginVerifier
